name: Co-op Translator

on:
  push:
    branches:
      - main

jobs:
  co-op-translator:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Co-op Translator
        run: |
          python -m pip install --upgrade pip
          pip install co-op-translator

      - name: Run Co-op Translator
        env:
          PYTHONIOENCODING: utf-8
          # Azure AI Service Credentials
          AZURE_AI_SERVICE_API_KEY: ${{ secrets.AZURE_AI_SERVICE_API_KEY }}
          AZURE_AI_SERVICE_ENDPOINT: ${{ secrets.AZURE_AI_SERVICE_ENDPOINT }}

          # Azure OpenAI Credentials
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_MODEL_NAME: ${{ secrets.AZURE_OPENAI_MODEL_NAME }}
          AZURE_OPENAI_CHAT_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT_NAME }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}

          # OpenAI Credentials
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
          OPENAI_CHAT_MODEL_ID: ${{ secrets.OPENAI_CHAT_MODEL_ID }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
        run: |
          # =====================================================================
          # IMPORTANT: Set your target languages here (REQUIRED CONFIGURATION)
          # =====================================================================
          # Example: Translate to Spanish, French, German. Add -y to auto-confirm.
          translate -l "all" -y # <--- MODIFY THIS LINE with your desired languages
          # translate -l "ar bn bg br cs da de el es fa fi fr he hi hr hu id it ja ko lt uk ur" -nb -y
          # translate -l "ar bn bg br cs da de el es fa fi fr" -y
          # translate -l "he hi hr hu id it ja ko lt uk ur" -y
          # translate -l "mo ms mr my ne nl no pa pl pt ro ru sk sl sr sv sw th tl tr tw vi zh hk" -nb -y
          # translate -l "mo ms mr my ne nl no pa pl pt ro ru" -nb -y
          # translate -l "sk sl sr sv sw th tl tr tw vi zh hk" -nb -y
          # Recommendation for large batches over 29 files run them in batches maximum github runner time is 6 hours
          # this set only translates markdown files 
          # translate -l "zh tw hk fr ja ko" -md -y
          # translate -l "pt es de fa pl hi" -md -y
          # translate -l "ru ar ur mo ja bn" -md -y
          # translate -l "mr ne pa br it tr" -md -y
          # translate -l "el th sv da no fi" -md -y
          # translate -l "nl he vi id ms tl" -md -y
          # translate -l "sw hu cs sk ro bg" -md -y
          # translate -l "sr hr sl uk my" -md -y
          # translate -l "de es fa fr hi ko" -md -y
          # translate -l "lt pl pt zh hk tw" -md -y
          
      - name: Authenticate GitHub App
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create Pull Request with translations
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "🌐 Update translations via Co-op Translator"
          title: "🌐 Update translations via Co-op Translator"
          body: |
            This PR updates translations for recent changes merged into the `main` branch.

            ### 📋 Summary of Changes
            - Translated markdown content has been added under the `translations/` directory
            - Translated images (if applicable) have been generated in the `translated_images/` directory

            🔁 Co-op Translator ensures that changes in links, structure, or inline elements in the original content are automatically reflected in all translated files.

            ---
            🌐 This pull request was automatically generated by [Co-op Translator](https://github.com/Azure/co-op-translator), powered by Azure AI.

          branch: update-translations
          base: main
          delete-branch: true
          add-paths: |
            translations/
            translated_images/
